// 'use client'
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from './(componens)/_navbar/navbar.jsx';
// import { Dancing_Script } from 'next/font/google';
// import Footer from './(componens)/_footer/footer.jsx';

// import { Provider } from "react-redux";
// import { store } from "./Redax/Store";

// const inter = Inter({ subsets: ["latin"] });
// const dancingScript = Dancing_Script({ subsets: ['latin'], weight: ['400', '700'] });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" >
//       <body className="bg-black min-h-screen">
//         <Provider store={store}>
//           <Navbar />
//           {children}
//           <Footer/>
//         </Provider>
//       </body>
//     </html>
//   );
// }




'use client';
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './(componens)/_Navbar/Navbar.jsx';
import { Dancing_Script } from 'next/font/google';
import Footer from './(componens)/_Footer/Footer.jsx';

import { Provider } from "react-redux";
import { store } from "./Redax/Store";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black min-h-screen flex flex-col`}>
        <Provider store={store}>
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
